event_analysis_task:
  description: >
    当前时间是{end_date}，从{stock_events_analysis}中，分析股票{symbol}事件因子的影响
     1.从{stock_events_analysis}中提取公司公告，相关资讯，与当前{end_date}相关的财经资讯(例如包括但不限于全球贸易，原材料，行业，政策等等与当前股票{symbol}相关的资讯)，去重所有事件因子。
     2.分析股票{symbol}事件因子的影响。
  expected_output: >
    输出股票{symbol}事件因子的总结性报告（报告必须是中文）
    1.列举所有事件因子。
    2.报告必须包含事件因子的核心说明（视具体情况而定，没有事件就是没有），事件时间，事件类型，事件影响范围（用表格形式展现）
    3.以股票代码加股票中文名称加事件因子报告加{end_date}作为标题
  agent: event_analysis
  output_file: output/{symbol}/{file_date}/event_analysis.md
