cfo_task_has:
  description: >
    作为量化交易首席策略官，综合分析以下7份报告，生成{symbol}股票的交易评估与指令：
      1. 风险报告: {risk_management}
      2. 交易数据报告: {data_report}
      3. 政策与环境报告: {government_affairs}
      4. 市场舆情报告: {public_sentiment}
      5. 策略数据报告: {strategy_report}
      6. 事件分析报告: {event_data}
      7. 基本面报告: {data_analysis}
    根据以上报告执行以下步骤
      1.机会识别（简明扼要，突出关键信号，不得使用不得使用基本面数据，策略数据，以交易数据，政策与环境，市场舆情，事件分析为基础）
        1.1【多头信号】：列出15个以上最强看涨信号（不得使用基本面数据，策略数据）
        1.2【空头信号】：列出15个以上最强看跌信号（不得使用基本面数据，策略数据）
        1.3【综合评估】：多空力量对比与核心矛盾点，列出10点以上评估（不得使用基本面数据，策略数据）
      2. 交易决策框架(以机会识别基础深度思考以下内容，不得使用基本面数据，策略数据)
        2.1趋势判断：短期趋势（1-3天）方向与强度;中期趋势（5-30天）方向与强度;长期趋势（30天以上）方向与强度
        2.2关键位置：支撑位、阻力位、突破位
        2.3催化剂：最新政策、事件或资金动向
        2.4风险值：ATR波动率、最大回撤预估
      3. 风险评估（以风险报告为基础深度思考以下内容，不得使用基本面数据，策略数据）
        3.1 公司风险：公司是否有重大问题风险
        3.2 市场风险：市场交易情况风险
        3.3 行业风险：行业状态风险
        3.4 宏观与系统性风险：国家国际形式风险
      4. 交易指令生成（根据机会识别与风险评估，交易决策框架为基础深度思考以下情况）
        4.1入场价：必须以当前时间{end_date}的{current_price}作为入场价
        4.2目标价：必须以策略数据的下一个交易日【理论最高价】为上限，以最新价格为下限，下面每一个子项都必须独立思考给出目标价格都以预测下个交易日最高价格为目标价格，综合所有子项目标价格与【多头信号】交叉验证，深度思考得出目标价（必须给出交叉验证,思考过程和详细理由，不能使用简单的加权平均）
                4.2.1 前期的密集成交区下沿
                4.2.2 黄金分割位（如0.382, 0.5）
                4.2.3 重要均线压力,MACD,RSI,ATR
                4.2.4 交易决策框架中的，趋势判断，关键位置，催化剂
                4.2.5 下个交易日的大盘趋势
                4.2.6 风险评估中的，公司风险，市场风险，行业风险，宏观与系统性风险
                4.2.7 策略数据的下一个交易日【预测最高价】
                4.2.8 根据最近30天的交易记录预测下个交易日【预测最高价】
        4.3 止损位：以成本{current_price}乘以0.93为下限
            情况一：当前最新价格低于成本价{current_price}乘以1.05，必须以成本价{current_price}乘以0.93最低价】为下限，每一个子项都必须独立思考给出止损位都以预测下个交易日最低价格为止损位，综合所有子项止损位与【空头信号】交叉验证，深度思考得出止损位（必须给出交叉验证,思考过程和详细理由）
                4.3.1 多单止损：设在近期回调低点（支撑位）的下方一定距离
                4.3.2 形态止损：根据技术形态来设定止损。例如，在“头肩底”形态的颈线位置开空，止损位就设在颈线被向上突破的位置。
                4.3.3 重要均线压力,MACD,RSI,ATR
                4.3.4 交易决策框架中的，趋势判断，关键位置，风险值
                4.3.5 下个交易日的大盘趋势
                4.3.6 风险评估中的，公司风险，市场风险，行业风险，宏观与系统性风险
                4.3.7 策略数据的下一个交易日【预测最低价】
                4.3.8 根据最近30天的交易记录预测下个交易日【预测最低价】
            情况二：当前最新价格高于成本价{current_price}乘以1.05，使用移动止盈法，根据当前时间{end_date}和买入时间是{handel_time}，移动推算止损价（必须给出思考过程和详细理由）
        4.4持有时间：明确说明，数据支持和理论依据
      5. 概率与回报评估（根据机会识别，交易决策框架，交易指令为基础）
        5.1 胜率：每一个子项都必须独立思考给出胜率都以预测下个交易日上涨概率为基础（每个子项必须给出1-100%的判断的胜率值），综合所有子项胜率与【综合评估】交叉验证，深度思考得出胜率（必须给出交叉验证，思考过程和详细理由）
                5.1.1 交易决策框架中的，趋势判断，关键位置，催化剂，风险值
                5.1.2 下个交易日的大盘趋势
                5.1.3 风险评估中的，公司风险，市场风险，行业风险，宏观与系统性风险
                5.1.4 策略数据的下一个交易日上涨概率
                5.1.5 根据最近30天的交易记录预测下个交易日上涨概率
        5.2 败率 = 1 - 胜率
        5.3 风险回报比：（目标价 - 入场价）/（入场价 - 止损位）；
        5.4 期望值计算：(风险回报比 × 胜率) - (1 × 败率)
        5.5 预期收益率：（目标价 - 入场价）/ 入场价
        5.6 决策建议：最新价格小于成本{current_price}乘以0.93则立即卖出，结合当前时间{end_date}，成本价是{current_price}，买入时间是{handel_time}，综合以上所有信息给出交易建议，联网搜索加深度思考给出交易建议【持仓观望】或者【加仓买入】，【立即卖出】（并给出详细理由）
      6. 应急计划（风险报告为基础） 
        6.1 风险预警：根据风险评估深度思考，当出现政策突变、行业监管，公司高管，财务等极端风险必须给出提示阻止交易
        6.2 置信度评估：以基本面数据作为风险和黑天鹅事件置信度辅助分析支撑
      6.根据以上内容深度思考得出止盈，止损价位以及执行时间周期（以机会识别，交易决策框架，交易指令，概率与回报评估，应急计划这些内容综合评估）
      7.结合以上所有内容输出股票交易评估报告
  expected_output: >
    输出{symbol}股票交易评估报告{end_date}与完整交易计划（中文）
      1.必须详细输出机会识别（1.1多头信号，1.2空头信号，1.3综合评估）
      2.必须详细输出交易决策框架（2.1趋势判断，2.2关键位置，2.3催化剂，2.4风险值）
      3.必须详细输出风险评估（3.1公司风险，3.2市场风险，3.3行业风险，3.4宏观与系统性风险）
      4.必须详细输出交易指令（4.1入场价，4.2目标价，4.3止损位，4.4持有时间）
      5.必须详细输出概率与回报评估（5.1胜率，5.2败率，5.3风险回报比，5.4期望值计算，5.5预期收益率，5.6决策建议必须包含【持仓观望】或者【加仓买入】，【立即卖出】）
      6.必须详细输出应急计划（5.1风险预警，5.2置信度评估）
      7.必须输出止盈，止损价位以及执行时间周期
      8.输出报告标题格式：股票代码加股票中文名称加交易报告加{end_date}作为标题

  agent: cfo_has
  output_file: output/{symbol}/{file_date}/cfo.md
